import { Program, AnchorProvider, Wallet, BN } from "@coral-xyz/anchor";
import {
  Connection,
  PublicKey,
  TransactionSignature,
  Keypair,
} from "@solana/web3.js";
import {
  getAssociatedTokenAddressSync,
  TOKEN_2022_PROGRAM_ID,
  TOKEN_PROGRAM_ID,
} from "@solana/spl-token";
import * as pda from "./accounts/pda.js";
import { generateNonce, hashKycData, hashTravelRuleData, toInstitutionId } from "./utils/hash.js";
import type {
  KycAttestation,
  CompliancePolicy,
  TransferRecord,
  TravelRuleRecord,
  CivicGatewayToken,
} from "./accounts/types.js";
import { CivicGatewayState } from "./accounts/types.js";

// The IDL type would be generated by Anchor — using `any` as placeholder
// In production: import type { Payclear } from "../target/types/payclear";
type PayclearProgram = Program<any>;

export interface PayClearClientConfig {
  connection: Connection;
  wallet: Wallet;
  programId: PublicKey;
}

export interface RegisterInstitutionParams {
  name: string;
  vaspCode: string; // max 16 chars
  jurisdiction: string; // 2-char ISO country code
  institutionAuthority: PublicKey;
}

export interface CreateAttestationParams {
  institutionId: Buffer;
  wallet: PublicKey;
  kycData: Record<string, unknown>;
  kycLevel: number;
  riskScore: number;
  expiresAt?: number; // Unix timestamp, 0 = no expiry
}

export interface PolicyParams {
  institutionId: Buffer;
  policyId?: Buffer; // auto-generated if not provided
  minKycLevel: number;
  maxRiskScore: number;
  travelRuleThreshold: bigint;
  requireBothAttested: boolean;
  allowedJurisdictions?: Buffer;
  blockedJurisdictions?: Buffer;
  maxTransferAmount: bigint;
  dailyLimit: bigint;
  requireCivicPass?: boolean;
  gatekeeperNetwork?: PublicKey;
}

export interface TransferParams {
  senderTokenAccount: PublicKey;
  receiverTokenAccount: PublicKey;
  receiverWallet: PublicKey;
  mint: PublicKey;
  amount: bigint;
  policyInstitution: PublicKey;
  policyId: Buffer;
  senderInstitution: PublicKey;
  receiverInstitution: PublicKey;
  nonce?: Buffer;
  travelRuleNonce?: Buffer; // Required if amount >= travel rule threshold
  tokenProgramId?: PublicKey; // Defaults to TOKEN_PROGRAM_ID
}

export interface TravelRuleParams {
  originatorInstitutionId: Buffer;
  beneficiaryInstitutionId: Buffer;
  beneficiaryWallet: PublicKey;
  amount: bigint;
  tokenMint: PublicKey;
  originatorData: Record<string, unknown>;
  beneficiaryData: Record<string, unknown>;
  nonce?: Buffer;
}

export interface TransferResult {
  signature: TransactionSignature;
  nonce: Buffer;
  transferRecord: PublicKey;
}

export class PayClearClient {
  public program: PayclearProgram;
  public programId: PublicKey;
  private provider: AnchorProvider;

  constructor(config: PayClearClientConfig) {
    this.programId = config.programId;
    this.provider = new AnchorProvider(config.connection, config.wallet, {
      commitment: "confirmed",
    });

    // In production, load the IDL from the deployed program or import it
    // For now, we construct the program with a placeholder
    this.program = new Program(
      { version: "0.1.0", name: "payclear", instructions: [], accounts: [], types: [], events: [], errors: [] } as any,
      this.provider
    );
  }

  // ─── Registry ────────────────────────────────────────────

  async initializeRegistry(): Promise<TransactionSignature> {
    const [registryPda] = pda.deriveRegistryPDA(this.programId);

    return this.program.methods
      .initializeRegistry()
      .accounts({
        registry: registryPda,
        authority: this.provider.wallet.publicKey,
        systemProgram: PublicKey.default,
      })
      .rpc();
  }

  // ─── Institutions ────────────────────────────────────────

  async registerInstitution(
    params: RegisterInstitutionParams
  ): Promise<TransactionSignature> {
    const institutionId = toInstitutionId(params.name);
    const [registryPda] = pda.deriveRegistryPDA(this.programId);
    const [institutionPda] = pda.deriveInstitutionPDA(
      institutionId,
      this.programId
    );

    const vaspCodeBuffer = Buffer.alloc(16);
    Buffer.from(params.vaspCode).copy(vaspCodeBuffer);

    const jurisdictionBuffer = Buffer.alloc(2);
    Buffer.from(params.jurisdiction).copy(jurisdictionBuffer);

    return this.program.methods
      .registerInstitution(
        Array.from(institutionId),
        Array.from(vaspCodeBuffer),
        Array.from(jurisdictionBuffer)
      )
      .accounts({
        registry: registryPda,
        institution: institutionPda,
        institutionAuthority: params.institutionAuthority,
        authority: this.provider.wallet.publicKey,
        systemProgram: PublicKey.default,
      })
      .rpc();
  }

  // ─── KYC Attestations ───────────────────────────────────

  async createKycAttestation(
    params: CreateAttestationParams
  ): Promise<TransactionSignature> {
    const [registryPda] = pda.deriveRegistryPDA(this.programId);
    const [institutionPda] = pda.deriveInstitutionPDA(
      params.institutionId,
      this.programId
    );
    const [attestationPda] = pda.deriveKycAttestationPDA(
      institutionPda,
      params.wallet,
      this.programId
    );

    const kycHash = hashKycData(params.kycData);

    return this.program.methods
      .createKycAttestation(
        Array.from(kycHash),
        params.kycLevel,
        params.riskScore,
        new BN(params.expiresAt ?? 0)
      )
      .accounts({
        registry: registryPda,
        institution: institutionPda,
        wallet: params.wallet,
        attestation: attestationPda,
        authority: this.provider.wallet.publicKey,
        systemProgram: PublicKey.default,
      })
      .rpc();
  }

  async revokeKycAttestation(
    institutionId: Buffer,
    wallet: PublicKey
  ): Promise<TransactionSignature> {
    const [institutionPda] = pda.deriveInstitutionPDA(
      institutionId,
      this.programId
    );
    const [attestationPda] = pda.deriveKycAttestationPDA(
      institutionPda,
      wallet,
      this.programId
    );

    return this.program.methods
      .revokeKycAttestation()
      .accounts({
        institution: institutionPda,
        attestation: attestationPda,
        authority: this.provider.wallet.publicKey,
      })
      .rpc();
  }

  async updateRiskScore(
    institutionId: Buffer,
    wallet: PublicKey,
    newRiskScore: number
  ): Promise<TransactionSignature> {
    const [institutionPda] = pda.deriveInstitutionPDA(
      institutionId,
      this.programId
    );
    const [attestationPda] = pda.deriveKycAttestationPDA(
      institutionPda,
      wallet,
      this.programId
    );

    return this.program.methods
      .updateRiskScore(newRiskScore)
      .accounts({
        institution: institutionPda,
        attestation: attestationPda,
        authority: this.provider.wallet.publicKey,
      })
      .rpc();
  }

  async getKycAttestation(
    institution: PublicKey,
    wallet: PublicKey
  ): Promise<KycAttestation | null> {
    const [attestationPda] = pda.deriveKycAttestationPDA(
      institution,
      wallet,
      this.programId
    );

    try {
      return await this.program.account.kycAttestation.fetch(attestationPda);
    } catch {
      return null;
    }
  }

  // ─── Compliance Policies ─────────────────────────────────

  async setCompliancePolicy(
    params: PolicyParams
  ): Promise<TransactionSignature> {
    const [institutionPda] = pda.deriveInstitutionPDA(
      params.institutionId,
      this.programId
    );

    const policyId = params.policyId ?? generateNonce();
    const [policyPda] = pda.derivePolicyPDA(
      institutionPda,
      policyId,
      this.programId
    );

    return this.program.methods
      .setCompliancePolicy({
        policyId: Array.from(policyId),
        minKycLevel: params.minKycLevel,
        maxRiskScore: params.maxRiskScore,
        travelRuleThreshold: new BN(params.travelRuleThreshold.toString()),
        requireBothAttested: params.requireBothAttested,
        allowedJurisdictions: Array.from(params.allowedJurisdictions ?? Buffer.alloc(64)),
        blockedJurisdictions: Array.from(params.blockedJurisdictions ?? Buffer.alloc(64)),
        maxTransferAmount: new BN(params.maxTransferAmount.toString()),
        dailyLimit: new BN(params.dailyLimit.toString()),
        requireCivicPass: params.requireCivicPass ?? false,
        gatekeeperNetwork: params.gatekeeperNetwork ?? PublicKey.default,
      })
      .accounts({
        institution: institutionPda,
        policy: policyPda,
        authority: this.provider.wallet.publicKey,
        systemProgram: PublicKey.default,
      })
      .rpc();
  }

  async getCompliancePolicy(
    institution: PublicKey,
    policyId: Buffer
  ): Promise<CompliancePolicy | null> {
    const [policyPda] = pda.derivePolicyPDA(
      institution,
      policyId,
      this.programId
    );

    try {
      return await this.program.account.compliancePolicy.fetch(policyPda);
    } catch {
      return null;
    }
  }

  // ─── Travel Rule ─────────────────────────────────────────

  async recordTravelRule(
    params: TravelRuleParams
  ): Promise<{ signature: TransactionSignature; nonce: Buffer }> {
    const nonce = params.nonce ?? generateNonce();

    const [originatorPda] = pda.deriveInstitutionPDA(
      params.originatorInstitutionId,
      this.programId
    );
    const [beneficiaryPda] = pda.deriveInstitutionPDA(
      params.beneficiaryInstitutionId,
      this.programId
    );
    const [travelRulePda] = pda.deriveTravelRulePDA(nonce, this.programId);

    const originatorDataHash = hashTravelRuleData(
      params.originatorData as any
    );
    const beneficiaryDataHash = hashTravelRuleData(
      params.beneficiaryData as any
    );

    const signature = await this.program.methods
      .recordTravelRule(
        Array.from(nonce),
        params.beneficiaryWallet,
        new BN(params.amount.toString()),
        params.tokenMint,
        Array.from(originatorDataHash),
        Array.from(beneficiaryDataHash)
      )
      .accounts({
        originatorInstitution: originatorPda,
        beneficiaryInstitution: beneficiaryPda,
        travelRuleRecord: travelRulePda,
        authority: this.provider.wallet.publicKey,
        systemProgram: PublicKey.default,
      })
      .rpc();

    return { signature, nonce };
  }

  async approveTravelRule(
    beneficiaryInstitutionId: Buffer,
    nonce: Buffer
  ): Promise<TransactionSignature> {
    const [beneficiaryPda] = pda.deriveInstitutionPDA(
      beneficiaryInstitutionId,
      this.programId
    );
    const [travelRulePda] = pda.deriveTravelRulePDA(nonce, this.programId);

    return this.program.methods
      .approveTravelRule()
      .accounts({
        beneficiaryInstitution: beneficiaryPda,
        travelRuleRecord: travelRulePda,
        authority: this.provider.wallet.publicKey,
      })
      .rpc();
  }

  // ─── Compliant Transfers ─────────────────────────────────

  async executeCompliantTransfer(
    params: TransferParams
  ): Promise<TransferResult> {
    const nonce = params.nonce ?? generateNonce();
    const tokenProgramId = params.tokenProgramId ?? TOKEN_PROGRAM_ID;

    const [registryPda] = pda.deriveRegistryPDA(this.programId);
    const [senderAttestationPda] = pda.deriveKycAttestationPDA(
      params.senderInstitution,
      this.provider.wallet.publicKey,
      this.programId
    );
    const [receiverAttestationPda] = pda.deriveKycAttestationPDA(
      params.receiverInstitution,
      params.receiverWallet,
      this.programId
    );
    const [policyPda] = pda.derivePolicyPDA(
      params.policyInstitution,
      params.policyId,
      this.programId
    );
    const [transferRecordPda] = pda.deriveTransferPDA(
      nonce,
      this.programId
    );

    const accounts: Record<string, PublicKey> = {
      sender: this.provider.wallet.publicKey,
      senderTokenAccount: params.senderTokenAccount,
      receiverTokenAccount: params.receiverTokenAccount,
      mint: params.mint,
      senderAttestation: senderAttestationPda,
      receiverAttestation: receiverAttestationPda,
      receiverWallet: params.receiverWallet,
      compliancePolicy: policyPda,
      transferRecord: transferRecordPda,
      registry: registryPda,
      tokenProgram: tokenProgramId,
      systemProgram: PublicKey.default,
    };

    // Add travel rule record if provided
    if (params.travelRuleNonce) {
      const [travelRulePda] = pda.deriveTravelRulePDA(
        params.travelRuleNonce,
        this.programId
      );
      accounts.travelRuleRecord = travelRulePda;
    }

    const signature = await this.program.methods
      .executeCompliantTransfer(
        Array.from(nonce),
        new BN(params.amount.toString())
      )
      .accounts(accounts)
      .rpc();

    return {
      signature,
      nonce,
      transferRecord: transferRecordPda,
    };
  }

  // ─── Transfer Hook Setup ─────────────────────────────────

  async initializeTransferHook(
    mint: PublicKey,
    policyInstitution: PublicKey,
    policyId: Buffer
  ): Promise<TransactionSignature> {
    const [extraAccountMetaListPda] = pda.deriveExtraAccountMetaListPDA(
      mint,
      this.programId
    );
    const [policyPda] = pda.derivePolicyPDA(
      policyInstitution,
      policyId,
      this.programId
    );

    return this.program.methods
      .initializeExtraAccountMetaList()
      .accounts({
        extraAccountMetaList: extraAccountMetaListPda,
        mint,
        policy: policyPda,
        authority: this.provider.wallet.publicKey,
        systemProgram: PublicKey.default,
      })
      .rpc();
  }

  // ─── Account Fetchers ────────────────────────────────────

  async getTransferRecord(nonce: Buffer): Promise<TransferRecord | null> {
    const [transferPda] = pda.deriveTransferPDA(nonce, this.programId);
    try {
      return await this.program.account.transferRecord.fetch(transferPda);
    } catch {
      return null;
    }
  }

  async getTravelRuleRecord(
    nonce: Buffer
  ): Promise<TravelRuleRecord | null> {
    const [travelRulePda] = pda.deriveTravelRulePDA(nonce, this.programId);
    try {
      return await this.program.account.travelRuleRecord.fetch(travelRulePda);
    } catch {
      return null;
    }
  }

  // ─── Civic Gateway Integration ──────────────────────────

  /**
   * Initialize the Civic-enhanced transfer hook for a mint.
   * Sets up ExtraAccountMetaList with Civic Gateway Token PDAs.
   */
  async initializeCivicTransferHook(
    mint: PublicKey,
    policyInstitution: PublicKey,
    policyId: Buffer,
    gatekeeperNetwork: PublicKey
  ): Promise<TransactionSignature> {
    const [extraAccountMetaListPda] = pda.deriveExtraAccountMetaListPDA(
      mint,
      this.programId
    );
    const [policyPda] = pda.derivePolicyPDA(
      policyInstitution,
      policyId,
      this.programId
    );

    return this.program.methods
      .initializeCivicExtraAccountMetaList()
      .accounts({
        extraAccountMetaList: extraAccountMetaListPda,
        mint,
        policy: policyPda,
        authority: this.provider.wallet.publicKey,
        systemProgram: PublicKey.default,
      })
      .rpc();
  }

  /**
   * Verify a wallet's Civic Pass on-chain by fetching and parsing
   * the Gateway Token account data.
   *
   * @param wallet - The wallet to check
   * @param gatekeeperNetwork - The gatekeeper network to verify against
   * @param gatewayProgramId - The Civic Gateway program ID
   * @returns The parsed CivicGatewayToken if found, null otherwise
   */
  async verifyCivicPass(
    wallet: PublicKey,
    gatekeeperNetwork: PublicKey,
    gatewayProgramId: PublicKey
  ): Promise<CivicGatewayToken | null> {
    const [gatewayTokenPda] = pda.deriveCivicGatewayTokenPDA(
      wallet,
      gatekeeperNetwork,
      gatewayProgramId
    );

    try {
      const accountInfo = await this.provider.connection.getAccountInfo(
        gatewayTokenPda
      );

      if (!accountInfo || !accountInfo.data || accountInfo.data.length < 66) {
        return null;
      }

      return PayClearClient.parseCivicGatewayToken(accountInfo.data);
    } catch {
      return null;
    }
  }

  /**
   * Parse raw Gateway Token account data into a CivicGatewayToken.
   *
   * Layout:
   *   [0]       features (1 byte)
   *   [1]       state    (1 byte)
   *   [2..34]   gatekeeper_network (32 bytes)
   *   [34..66]  issuing_gatekeeper (32 bytes)
   *   [66..74]  expire_time (i64 LE, optional)
   */
  static parseCivicGatewayToken(data: Buffer | Uint8Array): CivicGatewayToken {
    const buf = Buffer.from(data);
    const features = buf.readUInt8(0);
    const state = buf.readUInt8(1);
    const gatekeeperNetwork = new PublicKey(buf.subarray(2, 34));
    const issuingGatekeeper = new PublicKey(buf.subarray(34, 66));

    let expireTime = BigInt(0);
    if (buf.length >= 74) {
      expireTime = buf.readBigInt64LE(66);
    }

    return {
      features,
      state,
      gatekeeperNetwork,
      issuingGatekeeper,
      expireTime,
    };
  }

  // ─── Static PDA Helpers ──────────────────────────────────

  static deriveRegistryPDA = pda.deriveRegistryPDA;
  static deriveInstitutionPDA = pda.deriveInstitutionPDA;
  static deriveKycAttestationPDA = pda.deriveKycAttestationPDA;
  static derivePolicyPDA = pda.derivePolicyPDA;
  static deriveTravelRulePDA = pda.deriveTravelRulePDA;
  static deriveTransferPDA = pda.deriveTransferPDA;
  static deriveExtraAccountMetaListPDA = pda.deriveExtraAccountMetaListPDA;
  static deriveCivicGatewayTokenPDA = pda.deriveCivicGatewayTokenPDA;
}
